name: App Release
on: [push]
jobs:
  build-and-deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: node-env-setup
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: |
          npm install
      - name: build
        run: |
          npm run build --if-present -- --prod --base-href="https://qiu.xinx.me/"
        env:
          CI: true
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACTION_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
